import { MovieDetail, SearchResponse } from '../types';

export const CATEGORY_MAP: Record<string, string[]> = {
  'avengers': ["tt0848228", "tt4632448", "tt0107290", "tt0172495", "tt1392190", "tt0082971", "tt0499549", "tt0325980", "tt0095016", "tt0133093"],
  'funny': ["tt1119646", "tt0829482", "tt0357413", "tt1007898", "tt0109686", "tt0377062", "tt0087332", "tt0119528", "tt0443176", "tt0365748"],
  'story': ["tt0111161", "tt0109830", "tt0068646", "tt0110912", "tt0137523", "tt0108052", "tt0099685", "tt0120689", "tt2582802", "tt1285016"],
  'scary': ["tt1457767", "tt5052448", "tt0087800", "tt0081505", "tt0077651", "tt1396484", "tt7784604", "tt0054215", "tt6644204", "tt0070047"],
  'star': ["tt0816692", "tt1375666", "tt0076759", "tt1856101", "tt3659388", "tt2543167", "tt1454468", "tt1161413", "tt0103064", "tt0078748"],
  'honor': ["tt0903747", "tt5028030", "tt0944947", "tt0386676", "tt1475582", "tt0108778", "tt8111088", "tt3032476", "tt8162467", "tt2560140"],
  'rocky': ["tt0075148", "tt1210166", "tt0210945", "tt0878804", "tt1979320", "tt3503740", "tt0393162", "tt3076658", "tt1291584", "tt0117705"],
  'batman': ["tt0468569", "tt1877830", "tt4633694", "tt0371746", "tt3315342", "tt3501632", "tt0451279", "tt0317705", "tt0316654", "tt0409459"],
};

export const FALLBACK_MOVIES: MovieDetail[] = [
  {
    "imdbID": "tt0848228",
    "Title": "The Avengers",
    "Year": "2012",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0848228.jpg",
    "Rated": "11",
    "Released": "25 Apr 2012",
    "Runtime": "143 min",
    "Genre": "Science Fiction, Action, Adventure",
    "Director": "Joss Whedon",
    "Writer": "Jack Kirby",
    "Actors": "Joe Simon, Zak Penn, Robert Downey Jr., Chris Evans",
    "Plot": "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.0",
    "BoxOffice": "$1,518,815,515"
  },
  {
    "imdbID": "tt4632448",
    "Title": "Avengers: Endgame",
    "Year": "2019",
    "Type": "movie",
    "Poster": "/fallback-posters/tt4632448.jpg",
    "Rated": "11",
    "Released": "24 Apr 2019",
    "Runtime": "181 min",
    "Genre": "Adventure, Science Fiction, Action",
    "Director": "Bill Mantlo, Joe Russo",
    "Writer": "Christopher Markus, Stephen McFeely",
    "Actors": "Keith Giffen, Jim Starlin, Joe Simon, Larry Lieber",
    "Plot": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos\\' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$2,799,439,100"
  },
  {
    "imdbID": "tt0107290",
    "Title": "Jurassic Park",
    "Year": "1993",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0107290.jpg",
    "Rated": "11",
    "Released": "11 Jun 1993",
    "Runtime": "127 min",
    "Genre": "Adventure, Science Fiction",
    "Director": "Steven Spielberg",
    "Writer": "Michael Crichton, David Koepp",
    "Actors": "Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough",
    "Plot": "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.0",
    "BoxOffice": "$920,100,000"
  },
  {
    "imdbID": "tt0172495",
    "Title": "Gladiator",
    "Year": "2000",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0172495.jpg",
    "Rated": "15",
    "Released": "04 May 2000",
    "Runtime": "155 min",
    "Genre": "Action, Drama, Adventure",
    "Director": "Ridley Scott",
    "Writer": "David Franzoni, William Nicholson, John Logan",
    "Actors": "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed",
    "Plot": "After the death of Emperor Marcus Aurelius, his devious son takes power and demotes Maximus, one of Rome\\'s most capable generals who Marcus preferred. Eventually, Maximus is forced to become a gladiator and battle to the death against other men for the amusement of paying audiences.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$465,516,248"
  },
  {
    "imdbID": "tt1392190",
    "Title": "Mad Max: Fury Road",
    "Year": "2015",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1392190.jpg",
    "Rated": "15",
    "Released": "13 May 2015",
    "Runtime": "121 min",
    "Genre": "Action, Adventure, Science Fiction",
    "Director": "George Miller",
    "Writer": "Nico Lathouris, Brendan McCarthy",
    "Actors": "Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne",
    "Plot": "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
    "Language": "English",
    "Country": "Australia, United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$378,858,340"
  },
  {
    "imdbID": "tt0082971",
    "Title": "Raiders of the Lost Ark",
    "Year": "1981",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0082971.jpg",
    "Rated": "15",
    "Released": "12 Jun 1981",
    "Runtime": "115 min",
    "Genre": "Adventure, Action",
    "Director": "Steven Spielberg",
    "Writer": "Lawrence Kasdan, Philip Kaufman, George Lucas",
    "Actors": "Harrison Ford, Karen Allen, Paul Freeman, John Rhys-Davies",
    "Plot": "When Dr. Indiana Jones \u2013 the tweed-suited professor who just happens to be a celebrated archaeologist \u2013 is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.9",
    "BoxOffice": "$389,925,971"
  },
  {
    "imdbID": "tt0499549",
    "Title": "Avatar",
    "Year": "2009",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0499549.jpg",
    "Rated": "11",
    "Released": "16 Dec 2009",
    "Runtime": "162 min",
    "Genre": "Science Fiction, Action, Adventure",
    "Director": "James Cameron",
    "Writer": "N/A",
    "Actors": "Sam Worthington, Zoe Salda\u00f1a, Sigourney Weaver, Stephen Lang",
    "Plot": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$2,923,706,026"
  },
  {
    "imdbID": "tt0325980",
    "Title": "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Year": "2003",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0325980.jpg",
    "Rated": "11",
    "Released": "09 Jul 2003",
    "Runtime": "143 min",
    "Genre": "Adventure, Fantasy, Action",
    "Director": "Gore Verbinski",
    "Writer": "Ted Elliott, Terry Rossio",
    "Actors": "Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley",
    "Plot": "When wily pirate Captain Barbossa seizes Jack Sparrow\u2019s beloved ship, the Black Pearl, and kidnaps the governor\u2019s daughter, Elizabeth Swann, blacksmith Will Turner reluctantly teams up with the unpredictable pirate Jack to rescue her\u2014only to uncover a terrifying curse that turns Barbossa\u2019s crew into the undead.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$655,011,224"
  },
  {
    "imdbID": "tt0095016",
    "Title": "Die Hard",
    "Year": "1988",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0095016.jpg",
    "Rated": "15",
    "Released": "15 Jul 1988",
    "Runtime": "132 min",
    "Genre": "Action, Thriller",
    "Director": "John McTiernan",
    "Writer": "Roderick Thorp, Steven E. de Souza",
    "Actors": "Jeb Stuart, Bruce Willis, Alan Rickman, Alexander Godunov",
    "Plot": "High above the city of L.A. a team of terrorists has seized a building, taken hostages, and declared war. One man has manages to escape... An off-duty cop hiding somewhere inside. He\\'s alone, tired... and the only chance anyone has got.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$140,767,956"
  },
  {
    "imdbID": "tt0133093",
    "Title": "The Matrix",
    "Year": "1999",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0133093.jpg",
    "Rated": "15",
    "Released": "31 Mar 1999",
    "Runtime": "136 min",
    "Genre": "Action, Science Fiction",
    "Director": "Lana Wachowski, Lilly Wachowski",
    "Writer": "N/A",
    "Actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    "Plot": "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$463,517,383"
  },
  {
    "imdbID": "tt1119646",
    "Title": "The Hangover",
    "Year": "2009",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1119646.jpg",
    "Rated": "11",
    "Released": "02 Jun 2009",
    "Runtime": "100 min",
    "Genre": "Comedy",
    "Director": "Todd Phillips",
    "Writer": "Jon Lucas, Scott Moore",
    "Actors": "Bradley Cooper, Ed Helms, Zach Galifianakis, Justin Bartha",
    "Plot": "When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can\\'t seem to locate their best friend, Doug \u2013 who\\'s supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.3",
    "BoxOffice": "$469,310,836"
  },
  {
    "imdbID": "tt0829482",
    "Title": "Superbad",
    "Year": "2007",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0829482.jpg",
    "Rated": "15",
    "Released": "17 Aug 2007",
    "Runtime": "113 min",
    "Genre": "Comedy",
    "Director": "Greg Mottola",
    "Writer": "Evan Goldberg, Seth Rogen",
    "Actors": "Jonah Hill, Michael Cera, Christopher Mintz-Plasse, Bill Hader",
    "Plot": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.3",
    "BoxOffice": "$170,800,000"
  },
  {
    "imdbID": "tt0357413",
    "Title": "Anchorman: The Legend of Ron Burgundy",
    "Year": "2004",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0357413.jpg",
    "Rated": "11",
    "Released": "28 Jun 2004",
    "Runtime": "95 min",
    "Genre": "Comedy",
    "Director": "Adam McKay",
    "Writer": "Will Ferrell",
    "Actors": "Christina Applegate, Paul Rudd, Steve Carell, David Koechner",
    "Plot": "It\\'s the 1970s and San Diego anchorman Ron Burgundy is the top dog in local TV, but that\\'s all about to change when ambitious reporter Veronica Corningstone arrives as a new employee at his station.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.7",
    "BoxOffice": "$90,574,188"
  },
  {
    "imdbID": "tt1007898",
    "Title": "Step Brothers",
    "Year": "2008",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1007898.jpg",
    "Rated": "7",
    "Released": "25 Jul 2008",
    "Runtime": "98 min",
    "Genre": "Comedy",
    "Director": "Adam McKay",
    "Writer": "Will Ferrell, John C. Reilly",
    "Actors": "Richard Jenkins, Mary Steenburgen, Adam Scott, Kathryn Hahn",
    "Plot": "Brennan Huff and Dale Doback might be grown men. But that doesn\\'t stop them from living at home and turning into jealous, competitive stepbrothers when their single parents marry. Brennan\\'s constant competition with Dale strains his mom\\'s marriage to Dale\\'s dad, leaving everyone to wonder whether they\\'ll ever see eye to eye.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.6",
    "BoxOffice": "$128,100,000"
  },
  {
    "imdbID": "tt0109686",
    "Title": "Dumb and Dumber",
    "Year": "1994",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0109686.jpg",
    "Rated": "11",
    "Released": "16 Dec 1994",
    "Runtime": "107 min",
    "Genre": "Comedy",
    "Director": "Peter Farrelly",
    "Writer": "Bennett Yellin, Bobby Farrelly",
    "Actors": "Jim Carrey, Jeff Daniels, Lauren Holly, Teri Garr",
    "Plot": "Lloyd and Harry are two men whose stupidity is really indescribable. When Mary, a beautiful woman, loses an important suitcase with money before she leaves for Aspen, the two friends (who have found the suitcase) decide to return it to her. After some \"adventures\" they finally get to Aspen where, using the lost money they live it up and fight for Mary\\'s heart.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.7",
    "BoxOffice": "$247,275,374"
  },
  {
    "imdbID": "tt0377062",
    "Title": "National Lampoon's Christmas Vacation",
    "Year": "1989",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0377062.jpg",
    "Rated": "7",
    "Released": "30 Nov 1989",
    "Runtime": "97 min",
    "Genre": "Comedy",
    "Director": "Jeremiah S. Chechik",
    "Writer": "John Hughes",
    "Actors": "Chevy Chase, Beverly D&#39;Angelo, Juliette Lewis, Johnny Galecki",
    "Plot": "It\\'s Christmastime, and the Griswolds are preparing for a family seasonal celebration. But things never run smoothly for Clark, his wife Ellen, and their two kids. Clark\\'s continual bad luck is worsened by his obnoxious family guests, but he manages to keep going, knowing that his Christmas bonus is due soon.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.2",
    "BoxOffice": "$74,542,088"
  },
  {
    "imdbID": "tt0087332",
    "Title": "The Flower of My Secret",
    "Year": "1995",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0087332.jpg",
    "Rated": "15",
    "Released": "22 Sep 1995",
    "Runtime": "106 min",
    "Genre": "Drama, Romance",
    "Director": "Pedro Almod\u00f3var",
    "Writer": "N/A",
    "Actors": "Dorothy Parker, Marisa Paredes, Juan Echanove, Carme Elias",
    "Plot": "Middle-aged romance author Leo writes under a pseudonym, since she despises her own work. At home, her husband, who works overseas, is distant both physically and emotionally. As she reevaluates her life and writing, Leo is led to an unexpected relationship with \u00c1ngel, a sensitive newspaper editor.",
    "Language": "English",
    "Country": "Spain",
    "Awards": "N/A",
    "imdbRating": "6.8",
    "BoxOffice": "$19,000,000"
  },
  {
    "imdbID": "tt0119528",
    "Title": "Liar Liar",
    "Year": "1997",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0119528.jpg",
    "Rated": "7",
    "Released": "21 Mar 1997",
    "Runtime": "86 min",
    "Genre": "Comedy, Fantasy",
    "Director": "Tom Shadyac",
    "Writer": "Paul Guay, Stephen Mazur",
    "Actors": "Jim Carrey, Maura Tierney, Justin Cooper, Cary Elwes",
    "Plot": "Forced by his son\\'s birthday wish, fast-talking attorney and habitual liar Fletcher Reede must tell the truth for the next 24 hours.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.7",
    "BoxOffice": "$302,710,615"
  },
  {
    "imdbID": "tt0443176",
    "Title": "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
    "Year": "2006",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0443176.jpg",
    "Rated": "Btl",
    "Released": "01 Nov 2006",
    "Runtime": "84 min",
    "Genre": "Comedy",
    "Director": "Larry Charles",
    "Writer": "Peter Baynham, Anthony Hines, Sacha Baron Cohen, Dan Mazer, Todd Phillips",
    "Actors": "Ken Davitian, Luenell, Pamela Anderson, Bob Barr",
    "Plot": "Kazakh journalist Borat Sagdiyev travels to America to make a documentary. As he zigzags across the nation, Borat meets real people in real situations with hysterical consequences. His backwards behavior generates strong reactions around him exposing prejudices and hypocrisies in American culture.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.8",
    "BoxOffice": "$262,552,893"
  },
  {
    "imdbID": "tt0365748",
    "Title": "Shaun of the Dead",
    "Year": "2004",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0365748.jpg",
    "Rated": "15",
    "Released": "09 Apr 2004",
    "Runtime": "99 min",
    "Genre": "Horror, Comedy",
    "Director": "Edgar Wright",
    "Writer": "Simon Pegg",
    "Actors": "Nick Frost, Kate Ashfield, Lucy Davis, Dylan Moran",
    "Plot": "Shaun lives a supremely uneventful life, which revolves around his girlfriend, his mother, and, above all, his local pub. This gentle routine is threatened when the dead return to life and make strenuous attempts to snack on ordinary Londoners.",
    "Language": "English",
    "Country": "United Kingdom",
    "Awards": "N/A",
    "imdbRating": "7.5",
    "BoxOffice": "$39,396,175"
  },
  {
    "imdbID": "tt0111161",
    "Title": "The Shawshank Redemption",
    "Year": "1994",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0111161.jpg",
    "Rated": "15",
    "Released": "23 Sep 1994",
    "Runtime": "142 min",
    "Genre": "Drama, Crime",
    "Director": "Frank Darabont",
    "Writer": "N/A",
    "Actors": "Stephen King, Tim Robbins, Morgan Freeman, Bob Gunton",
    "Plot": "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.7",
    "BoxOffice": "$28,341,469"
  },
  {
    "imdbID": "tt0109830",
    "Title": "Forrest Gump",
    "Year": "1994",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0109830.jpg",
    "Rated": "11",
    "Released": "23 Jun 1994",
    "Runtime": "142 min",
    "Genre": "Comedy, Drama, Romance",
    "Director": "Robert Zemeckis",
    "Writer": "Winston Groom",
    "Actors": "Eric Roth, Tom Hanks, Robin Wright, Gary Sinise",
    "Plot": "A man with a low IQ has accomplished great things in his life and been present during significant historic events\u2014in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$677,387,716"
  },
  {
    "imdbID": "tt0068646",
    "Title": "The Godfather",
    "Year": "1972",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0068646.jpg",
    "Rated": "15",
    "Released": "14 Mar 1972",
    "Runtime": "175 min",
    "Genre": "Drama, Crime",
    "Director": "Francis Ford Coppola",
    "Writer": "Mario Puzo",
    "Actors": "Marlon Brando, Al Pacino, James Caan, Robert Duvall",
    "Plot": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.7",
    "BoxOffice": "$245,066,411"
  },
  {
    "imdbID": "tt0110912",
    "Title": "Pulp Fiction",
    "Year": "1994",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0110912.jpg",
    "Rated": "15",
    "Released": "10 Sep 1994",
    "Runtime": "154 min",
    "Genre": "Thriller, Crime, Comedy",
    "Director": "Quentin Tarantino",
    "Writer": "Roger Avary",
    "Actors": "John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis",
    "Plot": "A burger-loving hit man, his philosophical partner, a drug-addled gangster\\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$213,928,762"
  },
  {
    "imdbID": "tt0137523",
    "Title": "Fight Club",
    "Year": "1999",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0137523.jpg",
    "Rated": "15",
    "Released": "15 Oct 1999",
    "Runtime": "139 min",
    "Genre": "Drama, Thriller",
    "Director": "David Fincher",
    "Writer": "Chuck Palahniuk",
    "Actors": "Jim Uhls, Edward Norton, Brad Pitt, Helena Bonham Carter",
    "Plot": "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "$100,853,753"
  },
  {
    "imdbID": "tt0108052",
    "Title": "Schindler's List",
    "Year": "1993",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0108052.jpg",
    "Rated": "15",
    "Released": "15 Dec 1993",
    "Runtime": "195 min",
    "Genre": "Drama, History, War",
    "Director": "Steven Spielberg",
    "Writer": "Thomas Keneally",
    "Actors": "Steven Zaillian, Liam Neeson, Ben Kingsley, Ralph Fiennes",
    "Plot": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.6",
    "BoxOffice": "$321,365,567"
  },
  {
    "imdbID": "tt0099685",
    "Title": "GoodFellas",
    "Year": "1990",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0099685.jpg",
    "Rated": "15",
    "Released": "12 Sep 1990",
    "Runtime": "145 min",
    "Genre": "Drama, Crime",
    "Director": "Martin Scorsese",
    "Writer": "Nicholas Pileggi",
    "Actors": "Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco",
    "Plot": "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$47,072,327"
  },
  {
    "imdbID": "tt0120689",
    "Title": "The Green Mile",
    "Year": "1999",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0120689.jpg",
    "Rated": "15",
    "Released": "10 Dec 1999",
    "Runtime": "189 min",
    "Genre": "Fantasy, Drama, Crime",
    "Director": "Frank Darabont",
    "Writer": "N/A",
    "Actors": "Stephen King, Tom Hanks, David Morse, Bonnie Hunt",
    "Plot": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people\\'s ailments. When the cell block\\'s head guard, Paul Edgecomb, recognizes Coffey\\'s miraculous gift, he tries desperately to help stave off the condemned man\\'s execution.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$286,801,374"
  },
  {
    "imdbID": "tt2582802",
    "Title": "Whiplash",
    "Year": "2014",
    "Type": "movie",
    "Poster": "/fallback-posters/tt2582802.jpg",
    "Rated": "15",
    "Released": "10 Oct 2014",
    "Runtime": "107 min",
    "Genre": "Drama, Music, Thriller",
    "Director": "Damien Chazelle",
    "Writer": "N/A",
    "Actors": "Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist",
    "Plot": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "$50,307,484"
  },
  {
    "imdbID": "tt1285016",
    "Title": "The Social Network",
    "Year": "2010",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1285016.jpg",
    "Rated": "7",
    "Released": "01 Oct 2010",
    "Runtime": "121 min",
    "Genre": "Drama",
    "Director": "David Fincher",
    "Writer": "Aaron Sorkin",
    "Actors": "Jesse Eisenberg, Andrew Garfield, Armie Hammer, Justin Timberlake",
    "Plot": "In 2003, Harvard undergrad and computer programmer Mark Zuckerberg begins work on a new concept that eventually turns into the global social network known as Facebook. Six years later, Mark is one of the youngest billionaires ever, but his unprecedented success leads to both personal and legal complications when he ends up on the receiving end of two lawsuits, one involving his former friend.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.4",
    "BoxOffice": "$224,920,315"
  },
  {
    "imdbID": "tt1457767",
    "Title": "The Conjuring",
    "Year": "2013",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1457767.jpg",
    "Rated": "15",
    "Released": "18 Jul 2013",
    "Runtime": "112 min",
    "Genre": "Horror, Thriller",
    "Director": "James Wan",
    "Writer": "Chad Hayes, Carey Hayes",
    "Actors": "Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston",
    "Plot": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. Forced to confront a powerful entity, the Warrens find themselves caught in the most terrifying case of their lives.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.5",
    "BoxOffice": "$321,293,998"
  },
  {
    "imdbID": "tt5052448",
    "Title": "Get Out",
    "Year": "2017",
    "Type": "movie",
    "Poster": "/fallback-posters/tt5052448.jpg",
    "Rated": "15",
    "Released": "24 Feb 2017",
    "Runtime": "104 min",
    "Genre": "Mystery, Thriller, Horror",
    "Director": "Jordan Peele",
    "Writer": "N/A",
    "Actors": "Daniel Kaluuya, Allison Williams, Catherine Keener, Bradley Whitford",
    "Plot": "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family\\'s overly accommodating behavior as nervous attempts to deal with their daughter\\'s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$255,407,969"
  },
  {
    "imdbID": "tt0087800",
    "Title": "A Nightmare on Elm Street",
    "Year": "1984",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0087800.jpg",
    "Rated": "15",
    "Released": "09 Nov 1984",
    "Runtime": "91 min",
    "Genre": "Horror",
    "Director": "Wes Craven",
    "Writer": "N/A",
    "Actors": "Heather Langenkamp, Johnny Depp, Robert Englund, Amanda Wyss",
    "Plot": "Teenagers in a small town are dropping like flies, apparently in the grip of mass hysteria causing their suicides. A cop\\'s daughter, Nancy Thompson, traces the cause to child molester Fred Krueger, who was burned alive by angry parents many years before. Krueger has now come back in the dreams of his killers\\' children, claiming their lives as his revenge. Nancy and her boyfriend, Glen, must devise a plan to lure the monster out of the realm of nightmares and into the real world...",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.3",
    "BoxOffice": "$57,004,513"
  },
  {
    "imdbID": "tt0081505",
    "Title": "The Shining",
    "Year": "1980",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0081505.jpg",
    "Rated": "15",
    "Released": "23 May 1980",
    "Runtime": "144 min",
    "Genre": "Horror, Thriller",
    "Director": "Stanley Kubrick",
    "Writer": "Stephen King",
    "Actors": "Diane Johnson, Jack Nicholson, Shelley Duvall, Danny Lloyd",
    "Plot": "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren\\'t prepared for the madness that lurks within.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$44,781,695"
  },
  {
    "imdbID": "tt0077651",
    "Title": "Halloween",
    "Year": "1978",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0077651.jpg",
    "Rated": "15",
    "Released": "24 Oct 1978",
    "Runtime": "91 min",
    "Genre": "Horror, Thriller",
    "Director": "John Carpenter",
    "Writer": "Debra Hill",
    "Actors": "Donald Pleasence, Jamie Lee Curtis, Nancy Kyes, P. J. Soles",
    "Plot": "Fifteen years after murdering his sister on Halloween Night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$70,260,597"
  },
  {
    "imdbID": "tt1396484",
    "Title": "It",
    "Year": "2017",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1396484.jpg",
    "Rated": "15",
    "Released": "06 Sep 2017",
    "Runtime": "135 min",
    "Genre": "Horror, Thriller, Drama",
    "Director": "Andy Muschietti",
    "Writer": "Stephen King, Chase Palmer, Gary Dauberman",
    "Actors": "Cary Joji Fukunaga, Jaeden Martell, Jeremy Ray Taylor, Sophia Lillis",
    "Plot": "In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.2",
    "BoxOffice": "$719,766,009"
  },
  {
    "imdbID": "tt7784604",
    "Title": "Hereditary",
    "Year": "2018",
    "Type": "movie",
    "Poster": "/fallback-posters/tt7784604.jpg",
    "Rated": "15",
    "Released": "07 Jun 2018",
    "Runtime": "128 min",
    "Genre": "Horror, Mystery, Thriller",
    "Director": "Ari Aster",
    "Writer": "N/A",
    "Actors": "Toni Collette, Alex Wolff, Gabriel Byrne, Milly Shapiro",
    "Plot": "Following the death of the Leigh family matriarch, Annie and her children uncover disturbing secrets about their heritage. Their daily lives are not only impacted, but they also become entangled in a chilling fate from which they cannot escape, driving them to the brink of madness.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.3",
    "BoxOffice": "$87,796,204"
  },
  {
    "imdbID": "tt0054215",
    "Title": "Psycho",
    "Year": "1960",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0054215.jpg",
    "Rated": "15",
    "Released": "22 Jun 1960",
    "Runtime": "109 min",
    "Genre": "Horror, Thriller, Mystery",
    "Director": "Alfred Hitchcock",
    "Writer": "Robert Bloch",
    "Actors": "Joseph Stefano, Anthony Perkins, Janet Leigh, Vera Miles",
    "Plot": "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "$50,000,000"
  },
  {
    "imdbID": "tt6644204",
    "Title": "A Quiet Place",
    "Year": "2018",
    "Type": "movie",
    "Poster": "/fallback-posters/tt6644204.jpg",
    "Rated": "15",
    "Released": "03 Apr 2018",
    "Runtime": "91 min",
    "Genre": "Horror, Drama, Science Fiction",
    "Director": "John Krasinski",
    "Writer": "Bryan Woods, Scott Beck",
    "Actors": "Emily Blunt, Millicent Simmonds, Noah Jupe, Cade Woodward",
    "Plot": "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.4",
    "BoxOffice": "$340,955,294"
  },
  {
    "imdbID": "tt0070047",
    "Title": "The Movie Database",
    "Year": "2020",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0070047.jpg",
    "Rated": "PG-13",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Action",
    "Director": "N/A",
    "Writer": "N/A",
    "Actors": "Al Pacino, Marlon Brando, Diane Keaton, Robert Duvall",
    "Plot": "No description available.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.0",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt0816692",
    "Title": "Interstellar",
    "Year": "2014",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0816692.jpg",
    "Rated": "11",
    "Released": "05 Nov 2014",
    "Runtime": "169 min",
    "Genre": "Adventure, Drama, Science Fiction",
    "Director": "Christopher Nolan",
    "Writer": "Jonathan Nolan",
    "Actors": "Matthew McConaughey, Anne Hathaway, Michael Caine, Jessica Chastain",
    "Plot": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$746,606,706"
  },
  {
    "imdbID": "tt1375666",
    "Title": "Inception",
    "Year": "2010",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1375666.jpg",
    "Rated": "15",
    "Released": "15 Jul 2010",
    "Runtime": "148 min",
    "Genre": "Action, Science Fiction, Adventure",
    "Director": "Christopher Nolan",
    "Writer": "N/A",
    "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ken Watanabe, Tom Hardy",
    "Plot": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person\\'s idea into a target\\'s subconscious.",
    "Language": "English",
    "Country": "United States, United Kingdom",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "$839,030,630"
  },
  {
    "imdbID": "tt0076759",
    "Title": "Star Wars",
    "Year": "1977",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0076759.jpg",
    "Rated": "11",
    "Released": "25 May 1977",
    "Runtime": "121 min",
    "Genre": "Adventure, Action, Science Fiction",
    "Director": "George Lucas",
    "Writer": "N/A",
    "Actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
    "Plot": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$775,398,007"
  },
  {
    "imdbID": "tt1856101",
    "Title": "Blade Runner 2049",
    "Year": "2017",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1856101.jpg",
    "Rated": "15",
    "Released": "04 Oct 2017",
    "Runtime": "164 min",
    "Genre": "Science Fiction, Drama",
    "Director": "Philip K. Dick",
    "Writer": "Hampton Fancher, Michael Green",
    "Actors": "Denis Villeneuve, Ryan Gosling, Harrison Ford, Ana de Armas",
    "Plot": "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\\'s left of society into chaos. K\\'s discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$259,239,658"
  },
  {
    "imdbID": "tt3659388",
    "Title": "The Martian",
    "Year": "2015",
    "Type": "movie",
    "Poster": "/fallback-posters/tt3659388.jpg",
    "Rated": "11",
    "Released": "30 Sep 2015",
    "Runtime": "141 min",
    "Genre": "Science Fiction, Drama, Adventure",
    "Director": "Ridley Scott",
    "Writer": "Andy Weir",
    "Actors": "Drew Goddard, Matt Damon, Jessica Chastain, Kristen Wiig",
    "Plot": "During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.7",
    "BoxOffice": "$631,058,917"
  },
  {
    "imdbID": "tt2543167",
    "Title": "Arrival",
    "Year": "2016",
    "Type": "movie",
    "Poster": "/fallback-posters/tt2543167.jpg",
    "Rated": "11",
    "Released": "10 Nov 2016",
    "Runtime": "116 min",
    "Genre": "Drama, Science Fiction, Mystery",
    "Director": "Denis Villeneuve",
    "Writer": "Eric Heisserer",
    "Actors": "Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg",
    "Plot": "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.6",
    "BoxOffice": "$203,388,186"
  },
  {
    "imdbID": "tt1454468",
    "Title": "Gravity",
    "Year": "2013",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1454468.jpg",
    "Rated": "11",
    "Released": "03 Oct 2013",
    "Runtime": "91 min",
    "Genre": "Science Fiction, Thriller, Drama",
    "Director": "Alfonso Cuar\u00f3n",
    "Writer": "Jon\u00e1s Cuar\u00f3n",
    "Actors": "Sandra Bullock, George Clooney, Ed Harris, Orto Ignatiussen",
    "Plot": "Dr Ryan Stone, an engineer on her first space mission, and Matt Kowalski, an astronaut on his final expedition, have to survive in space after they are hit by debris while spacewalking.",
    "Language": "English",
    "Country": "United States, United Kingdom",
    "Awards": "N/A",
    "imdbRating": "7.2",
    "BoxOffice": "$723,192,705"
  },
  {
    "imdbID": "tt1161413",
    "Title": "Dune",
    "Year": "2021",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1161413.jpg",
    "Rated": "11",
    "Released": "15 Sep 2021",
    "Runtime": "155 min",
    "Genre": "Science Fiction, Adventure",
    "Director": "Denis Villeneuve",
    "Writer": "Frank Herbert, Eric Roth",
    "Actors": "Jon Spaihts, Timoth\u00e9e Chalamet, Rebecca Ferguson, Oscar Isaac",
    "Plot": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet\\'s exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity\\'s greatest potential-only those who can conquer their fear will survive.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$410,668,500"
  },
  {
    "imdbID": "tt0103064",
    "Title": "Terminator 2: Judgment Day",
    "Year": "1991",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0103064.jpg",
    "Rated": "15",
    "Released": "03 Jul 1991",
    "Runtime": "137 min",
    "Genre": "Action, Thriller, Science Fiction",
    "Director": "James Cameron",
    "Writer": "Gale Anne Hurd",
    "Actors": "William Wisher, Arnold Schwarzenegger, Linda Hamilton, Edward Furlong",
    "Plot": "Ten years after the events of the original, a reprogrammed T-800 is sent back in time to protect young John Connor from the shape-shifting T-1000. Together with his mother Sarah, he fights to stop Skynet from triggering a nuclear apocalypse.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$517,778,573"
  },
  {
    "imdbID": "tt0078748",
    "Title": "Alien",
    "Year": "1979",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0078748.jpg",
    "Rated": "15",
    "Released": "25 May 1979",
    "Runtime": "117 min",
    "Genre": "Horror, Science Fiction",
    "Director": "Ridley Scott",
    "Writer": "Dan O&#39;Bannon, Ronald Shusett",
    "Actors": "Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton",
    "Plot": "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.2",
    "BoxOffice": "$104,931,801"
  },
  {
    "imdbID": "tt0903747",
    "Title": "Game of Thrones",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt0903747.jpg",
    "Rated": "TV-MA",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Sci-Fi & Fantasy, Drama, Action & Adventure",
    "Director": "David Benioff, D. B. Weiss",
    "Writer": "N/A",
    "Actors": "Peter Dinklage, Kit Harington, Nikolaj Coster-Waldau, Lena Headey",
    "Plot": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night\\'s Watch, is all that stands between the realms of men and icy horrors beyond.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt5028030",
    "Title": "Stranger Things",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt5028030.jpg",
    "Rated": "TV-14",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Action & Adventure, Mystery, Sci-Fi & Fantasy",
    "Director": "Ross Duffer, Matt Duffer",
    "Writer": "N/A",
    "Actors": "Winona Ryder, David Harbour, Millie Bobby Brown, Finn Wolfhard",
    "Plot": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.6",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt0944947",
    "Title": "Breaking Bad",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt0944947.jpg",
    "Rated": "Fr\u00e5n 15 \u00e5r",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Drama, Crime",
    "Director": "Vince Gilligan",
    "Writer": "N/A",
    "Actors": "Bryan Cranston, Aaron Paul, Anna Gunn, RJ Mitte",
    "Plot": "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family\\'s financial future at any cost as he enters the dangerous world of drugs and crime.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.9",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt0386676",
    "Title": "The Office",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt0386676.jpg",
    "Rated": "Fr\u00e5n 11 \u00e5r",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Comedy",
    "Director": "Greg Daniels",
    "Writer": "N/A",
    "Actors": "Rainn Wilson, John Krasinski, Jenna Fischer, Leslie David Baker",
    "Plot": "The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.6",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt1475582",
    "Title": "Sherlock",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt1475582.jpg",
    "Rated": "Fr\u00e5n 11 \u00e5r",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Crime, Drama, Mystery",
    "Director": "Mark Gatiss, Steven Moffat",
    "Writer": "N/A",
    "Actors": "Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves",
    "Plot": "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    "Language": "English",
    "Country": "United Kingdom",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt0108778",
    "Title": "Friends",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt0108778.jpg",
    "Rated": "TV-14",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Comedy",
    "Director": "Marta Kauffman, David Crane",
    "Writer": "N/A",
    "Actors": "Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc",
    "Plot": "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt8111088",
    "Title": "The Mandalorian",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt8111088.jpg",
    "Rated": "TV-14",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Sci-Fi & Fantasy, Action & Adventure",
    "Director": "Jon Favreau",
    "Writer": "N/A",
    "Actors": "Pedro Pascal, Katee Sackhoff, Chris Bartlett, Carl Weathers",
    "Plot": "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt3032476",
    "Title": "Better Call Saul",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt3032476.jpg",
    "Rated": "TV-MA",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Crime, Drama",
    "Director": "Vince Gilligan, Peter Gould",
    "Writer": "N/A",
    "Actors": "Bob Odenkirk, Jonathan Banks, Rhea Seehorn, Patrick Fabian",
    "Plot": "Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is \u201cfixer\u201d Mike Ehrmantraut. The series tracks Jimmy\u2019s transformation into Saul Goodman, the man who puts \u201ccriminal\u201d in \u201ccriminal lawyer\".",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.7",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt8162467",
    "Title": "Chernobyl",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt8162467.jpg",
    "Rated": "Fr\u00e5n 15 \u00e5r",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Drama",
    "Director": "Craig Mazin",
    "Writer": "N/A",
    "Actors": "Jared Harris, Stellan Skarsg\u00e5rd, Emily Watson, Paul Ritter",
    "Plot": "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.7",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt2560140",
    "Title": "Attack on Titan",
    "Year": "2020",
    "Type": "series",
    "Poster": "/fallback-posters/tt2560140.jpg",
    "Rated": "TV-MA",
    "Released": "N/A",
    "Runtime": "120 min",
    "Genre": "Animation, Sci-Fi & Fantasy, Action & Adventure",
    "Director": "N/A",
    "Writer": "N/A",
    "Actors": "Yuki Kaji, Yui Ishikawa, Marina Inoue, Kisho Taniyama",
    "Plot": "100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls \u2013 but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill \u2013 or be devoured!",
    "Language": "English",
    "Country": "Japan",
    "Awards": "N/A",
    "imdbRating": "8.7",
    "BoxOffice": "N/A"
  },
  {
    "imdbID": "tt0075148",
    "Title": "Rocky",
    "Year": "1976",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0075148.jpg",
    "Rated": "15",
    "Released": "03 Dec 1976",
    "Runtime": "120 min",
    "Genre": "Drama",
    "Director": "John G. Avildsen",
    "Writer": "Sylvester Stallone",
    "Actors": "Talia Shire, Burt Young, Carl Weathers, Burgess Meredith",
    "Plot": "Rocky Balboa is a Philadelphia club fighter who seems to be going nowhere. But when a stroke of fate puts him in the ring with a world heavyweight champion, Rocky knows that it\\'s his one shot at the big time \u2014 a once-in-a-lifetime opportunity to go the distance and come out a winner!",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$117,253,345"
  },
  {
    "imdbID": "tt1210166",
    "Title": "Setup",
    "Year": "2011",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1210166.jpg",
    "Rated": "R",
    "Released": "17 Oct 2011",
    "Runtime": "85 min",
    "Genre": "Action, Crime, Drama, Thriller",
    "Director": "Mike Gunther",
    "Writer": "Mike Behrman",
    "Actors": "50 Cent, Ryan Phillippe, Bruce Willis, James Remar",
    "Plot": "A group of friends plan out a detailed heist that turns deadly when one betrays the other by taking off with the goods. Taking matters into his own hands, Sonny seeks out his revenge teaming up with the most dangerous mob boss in town to get back what is rightfully his. When he finally comes face to face with his longtime friend he will be forced to make a life changing choice.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "4.9",
    "BoxOffice": "$2,128,186"
  },
  {
    "imdbID": "tt0210945",
    "Title": "She Wore a Yellow Ribbon",
    "Year": "1949",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0210945.jpg",
    "Rated": "Btl",
    "Released": "22 Oct 1949",
    "Runtime": "104 min",
    "Genre": "Drama, Western",
    "Director": "John Ford",
    "Writer": "Frank S. Nugent, Laurence Stallings, James Warner Bellah",
    "Actors": "John Wayne, Joanne Dru, John Agar, Ben Johnson",
    "Plot": "On the eve of retirement, Captain Nathan Brittles takes out a last patrol to stop an impending massive Indian attack. Encumbered by women who must be evacuated, Brittles finds his mission imperiled.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.9",
    "BoxOffice": "$5,400,000"
  },
  {
    "imdbID": "tt0878804",
    "Title": "It's Complicated",
    "Year": "2009",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0878804.jpg",
    "Rated": "R",
    "Released": "23 Dec 2009",
    "Runtime": "121 min",
    "Genre": "Comedy, Romance",
    "Director": "Nancy Meyers",
    "Writer": "N/A",
    "Actors": "Meryl Streep, Alec Baldwin, Steve Martin, John Krasinski",
    "Plot": "Ten years after their divorce, Jane and Jake Adler unite for their son\\'s college graduation and unexpectedly end up sleeping together. But Jake is married, and Jane is embarking on a new romance with her architect. Now, she has to sort out her life\u2014just when she thought she had it all figured out.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.5",
    "BoxOffice": "$219,103,655"
  },
  {
    "imdbID": "tt1979320",
    "Title": "Rush",
    "Year": "2013",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1979320.jpg",
    "Rated": "15",
    "Released": "02 Sep 2013",
    "Runtime": "123 min",
    "Genre": "Drama, Action",
    "Director": "Ron Howard",
    "Writer": "Peter Morgan",
    "Actors": "Chris Hemsworth, Daniel Br\u00fchl, Olivia Wilde, Alexandra Maria Lara",
    "Plot": "In the 1970s, a rivalry propels race car drivers Niki Lauda and James Hunt to fame and glory \u2014 until a horrible accident threatens to end it all.",
    "Language": "English",
    "Country": "United States, United Kingdom",
    "Awards": "N/A",
    "imdbRating": "7.7",
    "BoxOffice": "$90,200,000"
  },
  {
    "imdbID": "tt3503740",
    "Title": "Ford v Ferrari",
    "Year": "2019",
    "Type": "movie",
    "Poster": "/fallback-posters/tt3503740.jpg",
    "Rated": "11",
    "Released": "13 Nov 2019",
    "Runtime": "153 min",
    "Genre": "Drama, Action, History",
    "Director": "James Mangold",
    "Writer": "Jez Butterworth, John-Henry Butterworth, Jason Keller",
    "Actors": "Matt Damon, Christian Bale, Jon Bernthal, Caitr\u00edona Balfe",
    "Plot": "American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.0",
    "BoxOffice": "$225,508,210"
  },
  {
    "imdbID": "tt0393162",
    "Title": "You Can Count on Me",
    "Year": "2000",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0393162.jpg",
    "Rated": "R",
    "Released": "03 Mar 2000",
    "Runtime": "111 min",
    "Genre": "Drama",
    "Director": "Kenneth Lonergan",
    "Writer": "N/A",
    "Actors": "Laura Linney, Mark Ruffalo, Matthew Broderick, Jon Tenney",
    "Plot": "A single mother\\'s life is thrown into turmoil after her struggling, rarely-seen younger brother returns to town.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.9",
    "BoxOffice": "$11,200,000"
  },
  {
    "imdbID": "tt3076658",
    "Title": "Creed",
    "Year": "2015",
    "Type": "movie",
    "Poster": "/fallback-posters/tt3076658.jpg",
    "Rated": "11",
    "Released": "25 Nov 2015",
    "Runtime": "133 min",
    "Genre": "Drama",
    "Director": "Ryan Coogler",
    "Writer": "Sylvester Stallone",
    "Actors": "Aaron Covington, Michael B. Jordan, Tessa Thompson, Phylicia Rash\u0101d",
    "Plot": "The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.4",
    "BoxOffice": "$173,600,000"
  },
  {
    "imdbID": "tt1291584",
    "Title": "Warrior",
    "Year": "2011",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1291584.jpg",
    "Rated": "15",
    "Released": "09 Sep 2011",
    "Runtime": "140 min",
    "Genre": "Drama, Action",
    "Director": "Gavin O&#39;Connor",
    "Writer": "Cliff Dorfman, Anthony Tambakis",
    "Actors": "Joel Edgerton, Tom Hardy, Nick Nolte, Jennifer Morrison",
    "Plot": "The youngest son of an alcoholic former boxer returns home, where he\\'s trained by his father for competition in a mixed martial arts tournament \u2013 a path that puts the fighter on a collision course with his estranged, older brother.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$23,300,000"
  },
  {
    "imdbID": "tt0117705",
    "Title": "Space Jam",
    "Year": "1996",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0117705.jpg",
    "Rated": "Btl",
    "Released": "15 Nov 1996",
    "Runtime": "87 min",
    "Genre": "Family, Animation, Science Fiction, Fantasy, Comedy",
    "Director": "Joe Pytka",
    "Writer": "Leo Benvenuti, Timothy Harris, Steve Rudnick, Herschel Weingrod",
    "Actors": "Michael Jordan, Wayne Knight, Theresa Randle, Manner Washington",
    "Plot": "With their freedom on the line, the Looney Tunes seek the help of NBA superstar Michael Jordan to win a basketball game against a team of moronic aliens.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "6.8",
    "BoxOffice": "$250,200,000"
  },
  {
    "imdbID": "tt0468569",
    "Title": "The Dark Knight",
    "Year": "2008",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0468569.jpg",
    "Rated": "15",
    "Released": "16 Jul 2008",
    "Runtime": "152 min",
    "Genre": "Action, Crime, Thriller",
    "Director": "Christopher Nolan",
    "Writer": "Bob Kane, David S. Goyer",
    "Actors": "Jonathan Nolan, Christian Bale, Heath Ledger, Aaron Eckhart",
    "Plot": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.5",
    "BoxOffice": "$1,004,558,444"
  },
  {
    "imdbID": "tt1877830",
    "Title": "The Batman",
    "Year": "2022",
    "Type": "movie",
    "Poster": "/fallback-posters/tt1877830.jpg",
    "Rated": "15",
    "Released": "01 Mar 2022",
    "Runtime": "177 min",
    "Genre": "Crime, Mystery, Thriller",
    "Director": "Matt Reeves",
    "Writer": "Bob Kane",
    "Actors": "Bill Finger, Peter Craig, Robert Pattinson, Zo\u00eb Kravitz",
    "Plot": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.7",
    "BoxOffice": "$772,775,278"
  },
  {
    "imdbID": "tt4633694",
    "Title": "Spider-Man: Into the Spider-Verse",
    "Year": "2018",
    "Type": "movie",
    "Poster": "/fallback-posters/tt4633694.jpg",
    "Rated": "7",
    "Released": "06 Dec 2018",
    "Runtime": "117 min",
    "Genre": "Animation, Action, Adventure, Science Fiction",
    "Director": "Rodney Rothman, Bob Persichetti, Peter Ramsey",
    "Writer": "Phil Lord",
    "Actors": "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali",
    "Plot": "Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson \"Kingpin\" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "8.4",
    "BoxOffice": "$394,884,133"
  },
  {
    "imdbID": "tt0371746",
    "Title": "Iron Man",
    "Year": "2008",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0371746.jpg",
    "Rated": "11",
    "Released": "30 Apr 2008",
    "Runtime": "126 min",
    "Genre": "Action, Science Fiction, Adventure",
    "Director": "Jon Favreau",
    "Writer": "Art Marcum, Mark Fergus, Hawk Ostby, Matt Holloway",
    "Actors": "Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow",
    "Plot": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.7",
    "BoxOffice": "$585,174,222"
  },
  {
    "imdbID": "tt3315342",
    "Title": "Logan",
    "Year": "2017",
    "Type": "movie",
    "Poster": "/fallback-posters/tt3315342.jpg",
    "Rated": "15",
    "Released": "28 Feb 2017",
    "Runtime": "137 min",
    "Genre": "Action, Drama, Science Fiction",
    "Director": "James Mangold",
    "Writer": "Michael Green, Scott Frank",
    "Actors": "Hugh Jackman, Dafne Keen, Patrick Stewart, Elizabeth Rodriguez",
    "Plot": "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan\\'s attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.8",
    "BoxOffice": "$619,021,436"
  },
  {
    "imdbID": "tt3501632",
    "Title": "Black Panther",
    "Year": "2018",
    "Type": "movie",
    "Poster": "/fallback-posters/tt3501632.jpg",
    "Rated": "11",
    "Released": "13 Feb 2018",
    "Runtime": "135 min",
    "Genre": "Action, Adventure, Science Fiction",
    "Director": "Ryan Coogler",
    "Writer": "Joe Robert Cole",
    "Actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong&#39;o, Danai Gurira",
    "Plot": "King T\\'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country\\'s new leader. However, T\\'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T\\'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan \\'special forces\\') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.4",
    "BoxOffice": "$1,349,926,083"
  },
  {
    "imdbID": "tt0451279",
    "Title": "Wonder Woman",
    "Year": "2017",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0451279.jpg",
    "Rated": "11",
    "Released": "30 May 2017",
    "Runtime": "141 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "William Moulton Marston",
    "Writer": "Allan Heinberg, Jason Fuchs, Zack Snyder",
    "Actors": "Patty Jenkins, Gal Gadot, Chris Pine, Connie Nielsen",
    "Plot": "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.2",
    "BoxOffice": "$823,970,682"
  },
  {
    "imdbID": "tt0317705",
    "Title": "The Incredibles",
    "Year": "2004",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0317705.jpg",
    "Rated": "7",
    "Released": "27 Oct 2004",
    "Runtime": "115 min",
    "Genre": "Action, Adventure, Animation, Family",
    "Director": "Brad Bird",
    "Writer": "N/A",
    "Actors": "Craig T. Nelson, Holly Hunter, Sarah Vowell, Spencer Fox",
    "Plot": "Bob Parr has given up his superhero days to log in time as an insurance adjuster and raise his three children with his formerly heroic wife in suburbia. But when he receives a mysterious assignment, it\\'s time to get back into costume.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.7",
    "BoxOffice": "$631,442,092"
  },
  {
    "imdbID": "tt0316654",
    "Title": "Spider-Man 2",
    "Year": "2004",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0316654.jpg",
    "Rated": "11",
    "Released": "25 Jun 2004",
    "Runtime": "127 min",
    "Genre": "Action, Adventure, Science Fiction",
    "Director": "Sam Raimi",
    "Writer": "Alvin Sargent",
    "Actors": "Tobey Maguire, Kirsten Dunst, James Franco, Alfred Molina",
    "Plot": "Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can\\'t act on his feelings for Mary Jane Watson, a girl he\\'s loved since childhood. A certain anger begins to brew in his best friend Harry Osborn as well...",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.3",
    "BoxOffice": "$788,976,453"
  },
  {
    "imdbID": "tt0409459",
    "Title": "Watchmen",
    "Year": "2009",
    "Type": "movie",
    "Poster": "/fallback-posters/tt0409459.jpg",
    "Rated": "15",
    "Released": "04 Mar 2009",
    "Runtime": "163 min",
    "Genre": "Mystery, Action, Science Fiction",
    "Director": "Zack Snyder",
    "Writer": "David Hayter, Alex Tse",
    "Actors": "Malin \u00c5kerman, Patrick Wilson, Billy Crudup, Matthew Goode",
    "Plot": "In a gritty and alternate 1985, the glory days of costumed vigilantes have been brought to a close by a government crackdown. But after one of the masked veterans is brutally murdered, an investigation into the killer is initiated. The reunited heroes set out to prevent their own destruction, but in doing so they uncover a sinister plot that puts all of humanity in grave danger.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "imdbRating": "7.4",
    "BoxOffice": "$185,258,983"
  }
];

export function getFallbackSearch(query: string, type?: string): SearchResponse {
  const normQuery = query.toLowerCase().trim();
  
  // Direct category route matching
  if (CATEGORY_MAP[normQuery]) {
    const ids = CATEGORY_MAP[normQuery];
    let results = FALLBACK_MOVIES.filter(m => ids.includes(m.imdbID));
    
    if (type && type !== 'all') {
      results = results.filter(m => m.Type === type);
    }
    
    const searchItems = results.map(({ imdbID, Title, Year, Type, Poster }) => ({
      imdbID,
      Title,
      Year,
      Type,
      Poster
    }));

    return {
      Search: searchItems,
      totalResults: searchItems.length.toString(),
      Response: searchItems.length > 0 ? 'True' : 'False'
    };
  }
  
  // Custom text-based search
  let results = FALLBACK_MOVIES.filter(m => {
    if (type && type !== 'all' && m.Type !== type) {
      return false;
    }
    
    return m.Title.toLowerCase().includes(normQuery) || 
           m.Genre.toLowerCase().includes(normQuery) ||
           m.Actors.toLowerCase().includes(normQuery);
  });

  // Default fallback if search query has no matches
  if (results.length === 0) {
    results = FALLBACK_MOVIES.filter(m => {
      if (type && type !== 'all' && m.Type !== type) {
        return false;
      }
      return true;
    }).slice(0, 10);
  }

  const searchItems = results.map(({ imdbID, Title, Year, Type, Poster }) => ({
    imdbID,
    Title,
    Year,
    Type,
    Poster
  }));

  return {
    Search: searchItems,
    totalResults: searchItems.length.toString(),
    Response: searchItems.length > 0 ? 'True' : 'False'
  };
}

export function getFallbackMovieById(id: string): MovieDetail | null {
  const movie = FALLBACK_MOVIES.find(m => m.imdbID === id);
  return movie || null;
}
